In [0]:
import pandas as pd

In [0]:
import matplotlib.pyplot as plt

In [0]:
data = pd.read_csv('Data_train_reduced.csv')

In [0]:
data

      Respondent.ID  ...  s13b.bottles.of.Deodorant.do.you.currently.own
0              3800  ...                                               3
1              3801  ...                                               4
2              3802  ...                                               2
3              3803  ...                                               3
4              3804  ...                                               3
5              3805  ...                                               2
6              3806  ...                                               5
7              3807  ...                                               3
8              3808  ...                                               4
9              3809  ...                                               2
10             3810  ...                                               3
11             3811  ...                                               5
12             3812  ...                                               3
13             3813  ...                                               1
14             3814  ...                                               1
15             3815  ...                                               3
16             3816  ...                                               6
17             3817  ...                                               3
18             3818  ...                                               3
19             3819  ...                                               1
20             3820  ...                                               5
21             3821  ...                                               4
22             3822  ...                                               1
23             3823  ...                                               6
24             3824  ...                                               6
25             3825  ...                                               2
26             3826  ...                                               3
27             3827  ...                                               6
28             3828  ...                                               2
29             3829  ...                                               5
...             ...  ...                                             ...
2470           5670  ...                                               4
2471           5671  ...                                               5
2472           5672  ...                                               1
2473           5673  ...                                               1
2474           5674  ...                                               2
2475           5675  ...                                               4
2476           5676  ...                                               1
2477           5677  ...                                               4
2478           5678  ...                                               4
2479           5679  ...                                               1
2480           5680  ...                                               1
2481           5681  ...                                               1
2482           5682  ...                                               2
2483           5683  ...                                               4
2484           5684  ...                                               3
2485           5685  ...                                               5
2486           5686  ...                                               3
2487           5687  ...                                               5
2488           5688  ...                                               2
2489           5689  ...                                               2
2490           5690  ...                                               1
2491           5691  ...                                               1
2492           5692  ...                                               2
2493           5693  ...                                               6
2494           5694  ...                                               6
2495           5695  ...                                               3
2496           5696  ...                                               2
2497           5697  ...                                               5
2498           5698  ...                                               4
2499           5699  ...                                               1

[2500 rows x 64 columns]

In [0]:
data['Product'].value_counts()

Deodorant H    500
Deodorant F    500
Deodorant B    500
Deodorant J    500
Deodorant G    500
Name: Product, dtype: int64

In [0]:
train_y = data['Instant.Liking']

      q1_1.personal.opinion.of.this.Deodorant  ...  s13b.bottles.of.Deodorant.do.you.currently.own
0                                           4  ...                                               3
1                                           5  ...                                               4
2                                           6  ...                                               2
3                                           4  ...                                               3
4                                           4  ...                                               3
5                                           5  ...                                               2
6                                           7  ...                                               5
7                                           5  ...                                               3
8                                           6  ...                                               4
9                                           4  ...                                               2
10                                          6  ...                                               3
11                                          5  ...                                               5
12                                          5  ...                                               3
13                                          3  ...                                               1
14                                          1  ...                                               1
15                                          6  ...                                               3
16                                          7  ...                                               6
17                                          4  ...                                               3
18                                          6  ...                                               3
19                                          7  ...                                               1
20                                          7  ...                                               5
21                                          6  ...                                               4
22                                          4  ...                                               1
23                                          6  ...                                               6
24                                          5  ...                                               6
25                                          3  ...                                               2
26                                          5  ...                                               3
27                                          5  ...                                               6
28                                          5  ...                                               2
29                                          7  ...                                               5
...                                       ...  ...                                             ...
2470                                        7  ...                                               4
2471                                        7  ...                                               5
2472                                        5  ...                                               1
2473                                        6  ...                                               1
2474                                        6  ...                                               2
2475                                        6  ...                                               4
2476                                        4  ...                                               1
2477                                        6  ...                                               4
2478                                        5  ...                                               4
2479                                        6  ...                                               1
2480                                        6  ...                                               1
2481                                        6  ...                                               1
2482                                        5  ...                                               2
2483                                        4  ...                                               4
2484                                        7  ...                                               3
2485                                        7  ...                                               5
2486                                        5  ...                                               3
2487                                        5  ...                                               5
2488                                        7  ...                                               2
2489                                        4  ...                                               2
2490                                        7  ...                                               1
2491                                        4  ...                                               1
2492                                        4  ...                                               2
2493                                        5  ...                                               6
2494                                        3  ...                                               6
2495                                        6  ...                                               3
2496                                        5  ...                                               2
2497                                        4  ...                                               5
2498                                        5  ...                                               4
2499                                        7  ...                                               1

[2500 rows x 60 columns]

In [0]:
for i in data.columns[4:]:
  data[i].fillna(data[i].median(skipna = True), inplace = True)

In [0]:
data.isnull().sum()

Respondent.ID                                              0
Product.ID                                                 0
Product                                                    0
Instant.Liking                                             0
q1_1.personal.opinion.of.this.Deodorant                    0
q2_all.words                                               0
q3_1.strength.of.the.Deodorant                             0
q4_1.artificial.chemical                                   0
q4_2.attractive                                            0
q4_3.bold                                                  0
q4_4.boring                                                0
q4_5.casual                                                0
q4_6.cheap                                                 0
q4_7.clean                                                 0
q4_8.easy.to.wear                                          0
q4_9.elegant                                               0
q4_10.feminine                                             0
q4_11.for.someone.like.me                                  0
q4_12.heavy                                                0
q4_13.high.quality                                         0
q4_14.long.lasting                                         0
q4_15.masculine                                            0
q4_16.memorable                                            0
q4_17.natural                                              0
q4_18.old.fashioned                                        0
q4_19.ordinary                                             0
q4_20.overpowering                                         0
q4_21.sharp                                                0
q4_22.sophisticated                                        0
q4_23.upscale                                              0
                                                          ..
q8.2                                                       0
q8.5                                                       0
q8.6                                                       0
q8.7                                                       0
q8.8                                                       0
q8.9                                                       0
q8.10                                                      0
q8.11                                                      0
q8.12                                                      0
q8.13                                                      0
q8.17                                                      0
q8.18                                                      0
q8.19                                                      0
q8.20                                                      0
q9.how.likely.would.you.be.to.purchase.this.Deodorant      0
q10.prefer.this.Deodorant.or.your.usual.Deodorant          0
q11.time.of.day.would.this.Deodorant.be.appropriate        0
q12.which.occasions.would.this.Deodorant.be.appropriate    0
Q13_Liking.after.30.minutes                                0
q14.Deodorant.overall.on.a.scale.from.1.to.10              0
ValSegb                                                    0
s7.involved.in.the.selection.of.the.cosmetic.products      0
s8.ethnic.background                                       0
s9.education                                               0
s10.income                                                 0
s11.marital.status                                         0
s12.working.status                                         0
s13.2                                                      0
s13a.b.most.often                                          0
s13b.bottles.of.Deodorant.do.you.currently.own             0
Length: 64, dtype: int64

In [0]:
train_X = data[data.columns[4:]]
train_X

      q1_1.personal.opinion.of.this.Deodorant  ...  s13b.bottles.of.Deodorant.do.you.currently.own
0                                           4  ...                                               3
1                                           5  ...                                               4
2                                           6  ...                                               2
3                                           4  ...                                               3
4                                           4  ...                                               3
5                                           5  ...                                               2
6                                           7  ...                                               5
7                                           5  ...                                               3
8                                           6  ...                                               4
9                                           4  ...                                               2
10                                          6  ...                                               3
11                                          5  ...                                               5
12                                          5  ...                                               3
13                                          3  ...                                               1
14                                          1  ...                                               1
15                                          6  ...                                               3
16                                          7  ...                                               6
17                                          4  ...                                               3
18                                          6  ...                                               3
19                                          7  ...                                               1
20                                          7  ...                                               5
21                                          6  ...                                               4
22                                          4  ...                                               1
23                                          6  ...                                               6
24                                          5  ...                                               6
25                                          3  ...                                               2
26                                          5  ...                                               3
27                                          5  ...                                               6
28                                          5  ...                                               2
29                                          7  ...                                               5
...                                       ...  ...                                             ...
2470                                        7  ...                                               4
2471                                        7  ...                                               5
2472                                        5  ...                                               1
2473                                        6  ...                                               1
2474                                        6  ...                                               2
2475                                        6  ...                                               4
2476                                        4  ...                                               1
2477                                        6  ...                                               4
2478                                        5  ...                                               4
2479                                        6  ...                                               1
2480                                        6  ...                                               1
2481                                        6  ...                                               1
2482                                        5  ...                                               2
2483                                        4  ...                                               4
2484                                        7  ...                                               3
2485                                        7  ...                                               5
2486                                        5  ...                                               3
2487                                        5  ...                                               5
2488                                        7  ...                                               2
2489                                        4  ...                                               2
2490                                        7  ...                                               1
2491                                        4  ...                                               1
2492                                        4  ...                                               2
2493                                        5  ...                                               6
2494                                        3  ...                                               6
2495                                        6  ...                                               3
2496                                        5  ...                                               2
2497                                        4  ...                                               5
2498                                        5  ...                                               4
2499                                        7  ...                                               1

[2500 rows x 60 columns]

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
model2 = LogisticRegression(solver='lbfgs')
model = LogisticRegression()

In [0]:
model2.fit(train_X,train_y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
model.fit(train_X,train_y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
test_data = pd.read_csv('test_data.csv')

In [0]:
for i in test_data.columns[4:]:
  test_data[i].fillna(test_data[i].median(skipna = True), inplace = True)

In [0]:
test_data['q1_1.personal.opinion.of.this.Deodorant']

0       7
1       6
2       6
3       5
4       6
5       7
6       5
7       6
8       5
9       5
10      6
11      6
12      6
13      5
14      3
15      6
16      6
17      7
18      6
19      6
20      7
21      4
22      2
23      5
24      6
25      6
26      5
27      4
28      6
29      6
       ..
5075    7
5076    5
5077    1
5078    5
5079    2
5080    1
5081    5
5082    6
5083    6
5084    5
5085    5
5086    1
5087    6
5088    7
5089    1
5090    7
5091    3
5092    4
5093    6
5094    5
5095    6
5096    5
5097    5
5098    5
5099    2
5100    6
5101    3
5102    4
5103    5
5104    6
Name: q1_1.personal.opinion.of.this.Deodorant, Length: 5105, dtype: int64

In [0]:
test_X = data[data.columns[4:]]

In [0]:
test_y = data['Instant.Liking']

In [0]:
pred1 = model.predict(test_X)

In [0]:
from sklearn.metrics import mean_absolute_error

In [0]:
print(mean_absolute_error(pred1,test_y))

0.0

In [0]:
print(mean_absolute_error(model2.predict(test_X),test_y))

0.0

In [0]:
pred1

array([1, 0, 0, ..., 1, 0, 0])

In [0]:
test_y

0       1
1       0
2       0
3       1
4       1
5       0
6       0
7       0
8       0
9       1
10      0
11      0
12      0
13      1
14      1
15      0
16      0
17      1
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      1
26      0
27      0
28      0
29      0
       ..
2470    0
2471    0
2472    0
2473    0
2474    0
2475    0
2476    1
2477    0
2478    0
2479    0
2480    0
2481    0
2482    0
2483    1
2484    0
2485    0
2486    0
2487    0
2488    0
2489    1
2490    0
2491    1
2492    1
2493    0
2494    1
2495    0
2496    0
2497    1
2498    0
2499    0
Name: Instant.Liking, Length: 2500, dtype: int64